### ISSUE TITLE
When I tried to log in this error occurred

### ISSUE THREAD

**Issue by mahiiyh** [Pasanlaksitha/AutoSeedr#2]
line 176, in get_token
    raise InvalidLogin("Invalid username and password combination.")
seedr_client.errors.InvalidLogin: Invalid username and password combination.

**Comment by Pasanlaksitha** [comment]
Thank you for bringing this to my attention. There's an issue with the login credentials provided. Your error message seems to be that the username and password combination is invalid.

To resolve this, please double-check your credentials in the configuration file `config.ini` .
